### ISSUE TITLE
Time zone issue on forwards summary page

### ISSUE THREAD

**Issue by ohenrik** [lncapital/torq#603]
Graph always shows me the 14th when it should show me the 15th

![image](https://user-images.githubusercontent.com/647617/232258879-9979276e-f725-4ca5-9ac2-0508d9a8f608.jpeg)

**Comment by maxwedwards** [comment]
I'm struggling to recreate this:

![Image](https://user-images.githubusercontent.com/1204616/232531629-d5f1be98-0fb9-42c2-828a-74b09d2ee4ec.png)

@ohenrik Do you have any more tips on how to recreate this?

**Comment by maxwedwards** [comment]
Clearing the api cache when changing timezones seems to fix this.

**Comment by djkazic** [comment]
I built this on master and still have it happen. I tried to trigger the API cache clearing by updating the node settings, but the rendering still shows off-by-one for the day.

**Comment by djkazic** [comment]
OK, I fixed it by resetting the database.

**Comment by djkazic** [comment]
Upon further testing, I have discovered that the weekly display is accurate if time zone is set to UTC. Otherwise, data is showing with the timestamp of tomorrow (2023/04/19).
![image](https://user-images.githubusercontent.com/3331929/232914784-ba766e65-492a-4530-9b87-e9773ba7e854.png)

Here is an example where timezone is set to UTC (proper behavior)
![image](https://user-images.githubusercontent.com/3331929/232914864-066f3480-d916-4985-ad00-e8d3c90be646.png)

**Comment by djkazic** [comment]
The forward occurred at `17:11` EST, but the history API gives me the date in a `ChannelHistoryRecords` struct as `2023-04-19T04:00:00Z`
